/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author PedroLeite
 */
public class Signos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Signos.class.getName());

    /**
     * Creates new form Signos
     */
    public Signos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        fundo = new javax.swing.JTabbedPane();
        inicio = new javax.swing.JPanel();
        areaDescobrirSigno = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfnome = new javax.swing.JTextField();
        cbdia = new javax.swing.JComboBox<>();
        cbMes = new javax.swing.JComboBox<>();
        btndescobrirSigno = new javax.swing.JToggleButton();
        areacompatilidade = new javax.swing.JPanel();
        fundoinicio = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        gemeos = new javax.swing.JPanel();
        fundogemeos = new javax.swing.JLabel();
        leao = new javax.swing.JPanel();
        fundocancer = new javax.swing.JLabel();
        escorpiao = new javax.swing.JPanel();
        fundolibra = new javax.swing.JLabel();
        sagitario = new javax.swing.JPanel();
        fundoescorpiao = new javax.swing.JLabel();
        painelsagitario = new javax.swing.JPanel();
        fundosagitario = new javax.swing.JLabel();
        peixes = new javax.swing.JPanel();
        fundoaquario = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        fundoinicio7 = new javax.swing.JLabel();
        aquario = new javax.swing.JPanel();
        fundocapricornio = new javax.swing.JLabel();
        touro = new javax.swing.JPanel();
        fundotouro = new javax.swing.JLabel();
        libra = new javax.swing.JPanel();
        fundoinicio10 = new javax.swing.JLabel();
        fundoaries = new javax.swing.JPanel();
        fundoAries = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        fundo.setForeground(new java.awt.Color(51, 51, 255));
        fundo.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N

        inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Descubra Seu Signo");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nome :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Dia do Nascimento :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Mês de Nascimento  :");

        tfnome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cbdia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbdia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "", "", "" }));

        cbMes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro", " " }));
        cbMes.addActionListener(this::cbMesActionPerformed);

        btndescobrirSigno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btndescobrirSigno.setText("Descobrir seu Signo");

        javax.swing.GroupLayout areaDescobrirSignoLayout = new javax.swing.GroupLayout(areaDescobrirSigno);
        areaDescobrirSigno.setLayout(areaDescobrirSignoLayout);
        areaDescobrirSignoLayout.setHorizontalGroup(
            areaDescobrirSignoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaDescobrirSignoLayout.createSequentialGroup()
                .addGroup(areaDescobrirSignoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btndescobrirSigno)
                    .addGroup(areaDescobrirSignoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(areaDescobrirSignoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(areaDescobrirSignoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(areaDescobrirSignoLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfnome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(areaDescobrirSignoLayout.createSequentialGroup()
                                    .addGroup(areaDescobrirSignoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(areaDescobrirSignoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(areaDescobrirSignoLayout.createSequentialGroup()
                            .addGap(95, 95, 95)
                            .addComponent(jLabel1))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        areaDescobrirSignoLayout.setVerticalGroup(
            areaDescobrirSignoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(areaDescobrirSignoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(areaDescobrirSignoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(areaDescobrirSignoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(areaDescobrirSignoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btndescobrirSigno)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        inicio.add(areaDescobrirSigno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 360, 230));

        javax.swing.GroupLayout areacompatilidadeLayout = new javax.swing.GroupLayout(areacompatilidade);
        areacompatilidade.setLayout(areacompatilidadeLayout);
        areacompatilidadeLayout.setHorizontalGroup(
            areacompatilidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        areacompatilidadeLayout.setVerticalGroup(
            areacompatilidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        inicio.add(areacompatilidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 360, 220));

        fundoinicio.setIcon(new javax.swing.ImageIcon("C:\\Users\\PedroLeite\\Documents\\ProjetoAppHoroscopo\\Horoscopo\\src\\main\\resources\\Assets\\fundo.jpg!d")); // NOI18N
        inicio.add(fundoinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTextField1.setText("digite seu dia de nacimento");
        inicio.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 240, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        inicio.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 40, -1, -1));
        inicio.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 60, -1, 16));

        fundo.addTab("Inicio", inicio);

        gemeos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fundogemeos.setIcon(new javax.swing.ImageIcon("C:\\Users\\PedroLeite\\Documents\\ProjetoAppHoroscopo\\Horoscopo\\src\\main\\resources\\Assets\\fundo.jpg!d")); // NOI18N
        gemeos.add(fundogemeos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 322, -1, -1));

        fundo.addTab("Gêmeos", gemeos);

        leao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fundocancer.setIcon(new javax.swing.ImageIcon("C:\\Users\\PedroLeite\\Documents\\ProjetoAppHoroscopo\\Horoscopo\\src\\main\\resources\\Assets\\fundo.jpg!d")); // NOI18N
        leao.add(fundocancer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 322, -1, -1));

        fundo.addTab("Câncer", leao);

        escorpiao.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fundolibra.setIcon(new javax.swing.ImageIcon("C:\\Users\\PedroLeite\\Documents\\ProjetoAppHoroscopo\\Horoscopo\\src\\main\\resources\\Assets\\fundo.jpg!d")); // NOI18N
        escorpiao.add(fundolibra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 322, -1, -1));

        fundo.addTab("Libra", escorpiao);

        sagitario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fundoescorpiao.setIcon(new javax.swing.ImageIcon("C:\\Users\\PedroLeite\\Documents\\ProjetoAppHoroscopo\\Horoscopo\\src\\main\\resources\\Assets\\fundo.jpg!d")); // NOI18N
        sagitario.add(fundoescorpiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 322, -1, -1));

        fundo.addTab("Escorpião", sagitario);

        painelsagitario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fundosagitario.setIcon(new javax.swing.ImageIcon("C:\\Users\\PedroLeite\\Documents\\ProjetoAppHoroscopo\\Horoscopo\\src\\main\\resources\\Assets\\fundo.jpg!d")); // NOI18N
        painelsagitario.add(fundosagitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 322, -1, -1));

        fundo.addTab("Sagitário", painelsagitario);

        peixes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fundoaquario.setIcon(new javax.swing.ImageIcon("C:\\Users\\PedroLeite\\Documents\\ProjetoAppHoroscopo\\Horoscopo\\src\\main\\resources\\Assets\\fundo.jpg!d")); // NOI18N
        peixes.add(fundoaquario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 322, -1, -1));

        fundo.addTab("Aquário", peixes);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fundoinicio7.setIcon(new javax.swing.ImageIcon("C:\\Users\\PedroLeite\\Documents\\ProjetoAppHoroscopo\\Horoscopo\\src\\main\\resources\\Assets\\fundo.jpg!d")); // NOI18N
        jPanel7.add(fundoinicio7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 322, -1, -1));

        fundo.addTab("Peixes", jPanel7);

        aquario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fundocapricornio.setIcon(new javax.swing.ImageIcon("C:\\Users\\PedroLeite\\Documents\\ProjetoAppHoroscopo\\Horoscopo\\src\\main\\resources\\Assets\\fundo.jpg!d")); // NOI18N
        aquario.add(fundocapricornio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 322, -1, -1));

        fundo.addTab("Capricónio", aquario);

        touro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fundotouro.setIcon(new javax.swing.ImageIcon("C:\\Users\\PedroLeite\\Documents\\ProjetoAppHoroscopo\\Horoscopo\\src\\main\\resources\\Assets\\fundo.jpg!d")); // NOI18N
        touro.add(fundotouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 322, -1, -1));

        fundo.addTab("Touro", touro);

        libra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fundoinicio10.setIcon(new javax.swing.ImageIcon("C:\\Users\\PedroLeite\\Documents\\ProjetoAppHoroscopo\\Horoscopo\\src\\main\\resources\\Assets\\fundo.jpg!d")); // NOI18N
        libra.add(fundoinicio10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 322, -1, -1));

        fundo.addTab("Virgem", libra);

        fundoaries.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fundoAries.setIcon(new javax.swing.ImageIcon("C:\\Users\\PedroLeite\\Documents\\ProjetoAppHoroscopo\\Horoscopo\\src\\main\\resources\\Assets\\fundo.jpg!d")); // NOI18N
        fundoaries.add(fundoAries, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 322, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        fundoaries.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        fundo.addTab("ARIES", fundoaries);

        getContentPane().add(fundo);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Signos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aquario;
    private javax.swing.JPanel areaDescobrirSigno;
    private javax.swing.JPanel areacompatilidade;
    private javax.swing.JToggleButton btndescobrirSigno;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JComboBox<String> cbdia;
    private javax.swing.JPanel escorpiao;
    private javax.swing.JTabbedPane fundo;
    private javax.swing.JLabel fundoAries;
    private javax.swing.JLabel fundoaquario;
    private javax.swing.JPanel fundoaries;
    private javax.swing.JLabel fundocancer;
    private javax.swing.JLabel fundocapricornio;
    private javax.swing.JLabel fundoescorpiao;
    private javax.swing.JLabel fundogemeos;
    private javax.swing.JLabel fundoinicio;
    private javax.swing.JLabel fundoinicio10;
    private javax.swing.JLabel fundoinicio7;
    private javax.swing.JLabel fundolibra;
    private javax.swing.JLabel fundosagitario;
    private javax.swing.JLabel fundotouro;
    private javax.swing.JPanel gemeos;
    private javax.swing.JPanel inicio;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel leao;
    private javax.swing.JPanel libra;
    private javax.swing.JPanel painelsagitario;
    private javax.swing.JPanel peixes;
    private javax.swing.JPanel sagitario;
    private javax.swing.JTextField tfnome;
    private javax.swing.JPanel touro;
    // End of variables declaration//GEN-END:variables
}
